### ISSUE TITLE
Show by default the burger menu

### ISSUE THREAD

**Issue by BorntraegerMarc** [hotforfeature/delightful-icons#2]
**I am submitting a**

- [x] Bug report
- [ ] New feature

**Description**

The animation (arrows) is shown on page loading:
![2017-11-01_20-17-45](https://user-images.githubusercontent.com/7549295/32292989-1283b63c-bf42-11e7-930b-eb9c110fb2ed.gif)

On slow devices/networks & large applications (where a lot is bootstrapped) the arrows can be shown up to 2 seconds.
This can be confusing for the user as first he sees the arrow and then it switches to the burger menu. 

Is there a way to show only the burger menu? And only do the animation when somebody clicks the icon. Not before...

**delightful-icons version**

0.1.1
**Polymer version**

2.0.0
**Which browsers does this affect?**
- [x] Chrome
- [x] Safari
- [ ] Firefox
- [ ] Edge
- [ ] IE11

**Comment by hotforfeature** [comment]
I may be able to do this in [the styles](https://github.com/hotforfeature/delightful-icons/blob/master/delightful-icons-style.html) by forcibly setting `--delightful-icons-duration` to `0s` like I do to essentially disable the animation on IE11.

Once the browser loads, I could then check if it supports SVG animation and remove the duration style from the document to cause future changes to animate. 

I'm not entirely when I should accept that the browser is ready though. I think the best solution is `window.onload`, though the animation may still play if the app itself has to do a lot of bootstrapping.

**Comment by BorntraegerMarc** [comment]
@hotforfeature why do you need to listen to when the browser is ready? Could you not set the property on the first click?

**Comment by hotforfeature** [comment]
The whole concept with these icons is that they immediately play their CSS animations. This means all the developer needs to do is change the name and the icon will immediately transition. They don't necessarily have to be triggered by a click.

They also aren't their own element, so we can't rely on JavaScript or properties to indicate when they're ready to start animating. We also can't rely on CSS classes on the host `<iron-icon>` consuming element because those classes won't be seen by the cloned SVG through Shadow DOM.

There are two ways we can solve this:

1. Wait for some indication that the app has finished loading and any future icon name changes should play their animations. This indicator could be a function the user calls, a DOM event, or a timeout.

2. Change the documentation to encourage users to pick a static icon first. We're using the same icons from `iron-icons`, so they could do something like this:

```html
<!-- Show static icon first -->
<paper-icon-button icon="menu"></paper-icon-button>
<script>
var button = document.querySelector('paper-icon-button');
button.addEventListener('click', function() {
  if (button.icon === 'menu') {
    button.icon = 'delightful-menu-arrow-back:arrow-back';
  } else if ( button.icon.indexOf(':menu') > -1) {
    button.icon = button.icon.replace(':menu', ':arrow-back');
  } else {
    button.icon = button.icon.replace(':arrow-back', ':menu');
  }
});
</script>
```

**Comment by BorntraegerMarc** [comment]
Great idea with initializing it with `icon="menu"`! Solved the problem for me. Issue can be closed from my side :)

**Comment by hotforfeature** [comment]
Gonna keep this open while I play around with some ideas. If I can't come up with an elegant solution, I'll add this caveat and workaround in the readme
